[package]
name = "tarea2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl_wrapper = { git = "https://github.com/zkwinkle/sdl_wrapper" , tag = "v0.1.0" }
rand = "0.8.0"
